// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

#include "gui/fonts.hpp"

#include <cstdio>

// The only translation unit that includes the generated bytes. It is about
// three megabytes of initialiser; compiling it twice would buy nothing.
#include "gui/font_assets.hpp"

namespace cascade::gui::fonts {
namespace {

ImFont* gUi = nullptr;
ImFont* gLegend = nullptr;
ImFont* gReading = nullptr;

// One face into the atlas.
//
// TWO THINGS HERE ARE NOT OPTIONAL.
//
// FontDataOwnedByAtlas = false, because the bytes are a constexpr array in
// read-only storage. ImGui's default is to take ownership and free() the
// pointer when the atlas is destroyed, which on this data is a heap corruption
// at shutdown - and shutdown is exactly where nobody looks for one.
//
// The const_cast, because AddFontFromMemoryTTF takes a non-const void* for the
// ownership case above. Neither of the rasterisers ImGui ships - stb_truetype
// or FreeType - writes to the font data, and with ownership disclaimed the
// atlas does not either.
ImFont* add(const unsigned char* data, unsigned int len, float size, const char* name) {
    ImFontConfig cfg;
    cfg.FontDataOwnedByAtlas = false;
    // Shows up in the Metrics/Debug window, so a font problem can be diagnosed
    // by looking rather than by guessing which of three faces is wrong.
    std::snprintf(cfg.Name, sizeof(cfg.Name), "%s", name);
    return ImGui::GetIO().Fonts->AddFontFromMemoryTTF(
        const_cast<unsigned char*>(data), static_cast<int>(len), size, &cfg);
}

// The fallback, in one place. ImGui::GetFont() is the face currently bound,
// which on the failure path is its own built-in bitmap one - wrong, legible,
// and never null.
ImFont* orCurrent(ImFont* f) { return f != nullptr ? f : ImGui::GetFont(); }

}  // namespace

ImFont* ui() { return orCurrent(gUi); }
ImFont* legend() { return orCurrent(gLegend); }
ImFont* reading() { return orCurrent(gReading); }

bool load() {
    ImGuiIO& io = ImGui::GetIO();

    // ORDER MATTERS ONLY IN ONE RESPECT: the first face added becomes ImGui's
    // default, so the UI face goes first and everything that never pushes a
    // font gets the right one for free.
    gUi = add(fontdata::kFontUiTtf, fontdata::kFontUiTtfLen, kUiSize, "FoxSDR UI");
    gLegend = add(fontdata::kFontLegendTtf, fontdata::kFontLegendTtfLen, kLegendSize,
                  "FoxSDR Legend");
    gReading = add(fontdata::kFontReadingTtf, fontdata::kFontReadingTtfLen, kReadingSize,
                   "FoxSDR Reading");

    if (gUi == nullptr || gLegend == nullptr || gReading == nullptr) {
        // Put the atlas back to a state that can definitely draw. A half-loaded
        // atlas is worse than none: it renders some strings and silently drops
        // others depending on which face a call site happened to push.
        io.Fonts->Clear();
        gUi = nullptr;
        gLegend = nullptr;
        gReading = nullptr;
        io.Fonts->AddFontDefault();
        return false;
    }

    // The style's base size has to agree with the face we just made default,
    // or every height derived from GetTextLineHeight is computed against a
    // size nothing is actually drawn at.
    ImGui::GetStyle().FontSizeBase = kUiSize;
    io.FontDefault = gUi;
    return true;
}

}  // namespace cascade::gui::fonts
