// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

#include "gui/fonts.hpp"

#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <string>

// The only translation unit that includes the generated bytes. It is about
// three megabytes of initialiser; compiling it twice would buy nothing.
#include "gui/font_assets.hpp"
#include "gui/font_blobs.hpp"

namespace cascade::gui::fonts {
namespace {

ImFont* gUi = nullptr;
ImFont* gLegend = nullptr;
ImFont* gReading = nullptr;

// One face into the atlas.
//
// TWO THINGS HERE ARE NOT OPTIONAL.
//
// FontDataOwnedByAtlas = false, because the bytes are a constexpr array in
// read-only storage. ImGui's default is to take ownership and free() the
// pointer when the atlas is destroyed, which on this data is a heap corruption
// at shutdown - and shutdown is exactly where nobody looks for one.
//
// The const_cast, because AddFontFromMemoryTTF takes a non-const void* for the
// ownership case above. Neither of the rasterisers ImGui ships - stb_truetype
// or FreeType - writes to the font data, and with ownership disclaimed the
// atlas does not either.
ImFont* add(const unsigned char* data, unsigned int len, float size, const char* name) {
    ImFontConfig cfg;
    cfg.FontDataOwnedByAtlas = false;
    // Shows up in the Metrics/Debug window, so a font problem can be diagnosed
    // by looking rather than by guessing which of three faces is wrong.
    std::snprintf(cfg.Name, sizeof(cfg.Name), "%s", name);
    return ImGui::GetIO().Fonts->AddFontFromMemoryTTF(
        const_cast<unsigned char*>(data), static_cast<int>(len), size, &cfg);
}

// The fallback, in one place. ImGui::GetFont() is the face currently bound,
// which on the failure path is its own built-in bitmap one - wrong, legible,
// and never null.
ImFont* orCurrent(ImFont* f) { return f != nullptr ? f : ImGui::GetFont(); }

// A face from the OPERATING SYSTEM'S font directory, for the two roles that
// are lettered in Georgia (0.84.0). Not embedded, and that is a licence
// fact rather than a preference: Georgia is Microsoft's typeface, licensed
// with Windows for use on that machine, and the redistribution the embedded
// OFL faces permit is exactly what its licence does not. So the bytes are
// read from where Windows keeps them and never shipped. Returns null when the
// file is not there - a Linux desktop, or a Windows install with the font
// removed - and the caller falls back to the embedded face, which is why the
// embedded face is still in the binary.
ImFont* addSystem(const std::string& path, float size, const char* name) {
    if (path.empty() || !std::filesystem::exists(path)) { return nullptr; }
    ImFontConfig cfg;
    std::snprintf(cfg.Name, sizeof(cfg.Name), "%s", name);
    return ImGui::GetIO().Fonts->AddFontFromFileTTF(path.c_str(), size, &cfg);
}

bool gSystemSerif = false;

}  // namespace

std::string systemFontPath(const char* file) {
    if (file == nullptr || file[0] == '\0') { return {}; }
#ifdef _WIN32
    // %WINDIR%\Fonts is where every Windows since 3.1 has kept them; the
    // environment variable is honoured over the usual drive letter because a
    // Windows installed anywhere else still sets it.
    const char* win = std::getenv("WINDIR");
    const std::string root = (win != nullptr && win[0] != '\0') ? std::string(win) : "C:\\Windows";
    return root + "\\Fonts\\" + file;
#else
    (void)file;
    return {};
#endif
}

bool usingSystemSerif() { return gSystemSerif; }

ImFont* ui() { return orCurrent(gUi); }
ImFont* legend() { return orCurrent(gLegend); }
ImFont* reading() { return orCurrent(gReading); }

bool load() {
    ImGuiIO& io = ImGui::GetIO();

    // ORDER MATTERS ONLY IN ONE RESPECT: the first face added becomes ImGui's
    // default, so the UI face goes first and everything that never pushes a
    // font gets the right one for free.
    //
    // GEORGIA FIRST, SAIRA IF IT IS NOT THERE. The two are taken as a pair:
    // a Georgia body with a Saira Condensed legend, or the reverse, would be
    // two typefaces that were never designed to sit together, so if either
    // file is missing both roles fall back to the embedded pair.
    ImFont* sysUi = addSystem(systemFontPath("georgia.ttf"), kUiSize, "FoxSDR UI (Georgia)");
    ImFont* sysLegend =
        sysUi != nullptr ? addSystem(systemFontPath("georgiab.ttf"), kLegendSize,
                                     "FoxSDR Legend (Georgia Bold)")
                         : nullptr;
    gSystemSerif = sysUi != nullptr && sysLegend != nullptr;
    if (gSystemSerif) {
        gUi = sysUi;
        gLegend = sysLegend;
    } else {
        // A half-added pair would leave one Georgia face in the atlas that
        // nothing references; clear so the fallback pair is added cleanly.
        io.Fonts->Clear();
        gUi = add(fontdata::kFontUiTtf, fontdata::kFontUiTtfLen, kUiSize, "FoxSDR UI");
        gLegend = add(fontdata::kFontLegendTtf, fontdata::kFontLegendTtfLen, kLegendSize,
                      "FoxSDR Legend");
    }
    gReading = add(fontdata::kFontReadingTtf, fontdata::kFontReadingTtfLen, kReadingSize,
                   "FoxSDR Reading");

    if (gUi == nullptr || gLegend == nullptr || gReading == nullptr) {
        // Put the atlas back to a state that can definitely draw. A half-loaded
        // atlas is worse than none: it renders some strings and silently drops
        // others depending on which face a call site happened to push.
        io.Fonts->Clear();
        gUi = nullptr;
        gLegend = nullptr;
        gReading = nullptr;
        io.Fonts->AddFontDefault();
        return false;
    }

    // The style's base size has to agree with the face we just made default,
    // or every height derived from GetTextLineHeight is computed against a
    // size nothing is actually drawn at.
    ImGui::GetStyle().FontSizeBase = kUiSize;
    io.FontDefault = gUi;
    return true;
}

// --- Raw bytes, for callers that are not ImGui -------------------------------
//
// These exist so the remote interface can serve the SAME faces to a browser;
// see gui/font_blobs.hpp. They are defined here because this is already the one
// translation unit that includes font_assets.hpp, and the whole point of that
// restriction is not to compile three megabytes of initialiser twice.
//
// They return the upstream files unchanged, which is what the SIL Open Font
// License requires of a Reserved Font Name: redistribution yes, modification
// while keeping the name no.

const unsigned char* uiTtf() { return fontdata::kFontUiTtf; }
std::size_t uiTtfLen() { return fontdata::kFontUiTtfLen; }

const unsigned char* legendTtf() { return fontdata::kFontLegendTtf; }
std::size_t legendTtfLen() { return fontdata::kFontLegendTtfLen; }

const unsigned char* readingTtf() { return fontdata::kFontReadingTtf; }
std::size_t readingTtfLen() { return fontdata::kFontReadingTtfLen; }

}  // namespace cascade::gui::fonts
