// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

#include "gui/fonts.hpp"

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <map>
#include <memory>
#include <string>
#include <vector>

#include "core/i18n.hpp"
#include "core/scripts.hpp"
#include "core/utf8_text.hpp"
#include "gui/font_probe.hpp"

// The only translation unit that includes the generated bytes. It is about
// three megabytes of initialiser; compiling it twice would buy nothing.
#include "gui/font_assets.hpp"
#include "gui/font_blobs.hpp"

namespace cascade::gui::fonts {
namespace {

namespace scripts = cascade::core::scripts;

#ifdef _WIN32
constexpr bool kWindows = true;
#else
constexpr bool kWindows = false;
#endif

ImFont* gUi = nullptr;
ImFont* gLegend = nullptr;
ImFont* gReading = nullptr;

// The fallback, in one place. ImGui::GetFont() is the face currently bound,
// which on the failure path is its own built-in bitmap one - wrong, legible,
// and never null.
ImFont* orCurrent(ImFont* f) { return f != nullptr ? f : ImGui::GetFont(); }

bool gSystemSerif = false;

// --- font files from the operating system -----------------------------------
//
// Georgia (0.84.0) and the CJK faces are read from where the system keeps
// them and never shipped: Georgia is Microsoft's typeface, licensed with
// Windows for use on that machine, and the redistribution the embedded OFL
// faces permit is exactly what its licence does not; the CJK faces are that
// AND tens of megabytes each (core/scripts.hpp).
//
// PINNED FILES STAY IN MEMORY FOR THE LIFE OF THE PROCESS. The atlas is given
// their bytes with FontDataOwnedByAtlas = false, and Chain hands pointers into
// them to its callers, so a pinned file is never freed. A file is pinned only
// when a face in it is actually put in a chain; merely ASKING whether a
// language can be drawn reads the file, answers, and lets the bytes go.
using Bytes = std::shared_ptr<const std::vector<unsigned char>>;
std::map<std::string, Bytes> gPinned;

Bytes readFile(const std::string& path) {
    if (path.empty()) { return nullptr; }
    if (const auto it = gPinned.find(path); it != gPinned.end()) { return it->second; }
    std::error_code ec;
    if (!std::filesystem::is_regular_file(path, ec)) { return nullptr; }
    std::ifstream f(path, std::ios::binary);
    if (!f) { return nullptr; }
    auto bytes = std::make_shared<std::vector<unsigned char>>(
        (std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());
    if (bytes->empty()) { return nullptr; }
    return bytes;
}

Bytes pin(const std::string& path) {
    Bytes b = readFile(path);
    if (b != nullptr) { gPinned.emplace(path, b); }
    return b;
}

ChainFace embedded(const char* label, const unsigned char* data, unsigned int len) {
    return ChainFace{label, data, len, 0};
}

// The Georgia pair, when this machine has both files. Read once.
bool gGeorgiaTried = false;
ChainFace gGeorgia;
ChainFace gGeorgiaBold;

bool haveGeorgia() {
    if (!gGeorgiaTried) {
        gGeorgiaTried = true;
        const Bytes r = pin(systemFontPath("georgia.ttf"));
        const Bytes b = r != nullptr ? pin(systemFontPath("georgiab.ttf")) : nullptr;
        if (r != nullptr && b != nullptr) {
            gGeorgia = ChainFace{"Georgia", r->data(), r->size(), 0};
            gGeorgiaBold = ChainFace{"Georgia Bold", b->data(), b->size(), 0};
        }
    }
    return gGeorgia.data != nullptr;
}

// --- the system CJK faces -----------------------------------------------------
//
// For each CJK standard, the usable faces this machine has, found lazily and
// in core/scripts.hpp's order of preference: a candidate is usable when its
// file exists and a face in it has every probe character. Usually only the
// first is ever looked for; a second is sought only when a catalogue uses a
// character the first lacks (Yu Gothic has no 简, say).
struct CjkPick {
    std::string path;
    std::string label;  // "msyh.ttc#1"
    int index = 0;
};
struct CjkScan {
    std::vector<scripts::SystemFace> candidates;
    std::size_t next = 0;
    bool started = false;
    std::vector<CjkPick> found;
};
std::map<int, CjkScan> gScans;

const CjkPick* usableCjk(scripts::CjkFace face, std::size_t k) {
    CjkScan& s = gScans[static_cast<int>(face)];
    if (!s.started) {
        s.started = true;
        s.candidates = scripts::systemCandidates(face, kWindows);
    }
    while (s.found.size() <= k && s.next < s.candidates.size()) {
        const scripts::SystemFace& c = s.candidates[s.next++];
        const std::string path = kWindows ? systemFontPath(c.path.c_str()) : c.path;
        const Bytes b = readFile(path);
        if (b == nullptr) { continue; }
        const int index = fontprobe::pickFace(b->data(), b->size(), c.nameHint,
                                              scripts::probeCodePoints(face));
        if (index < 0) { continue; }
        const std::string file = std::filesystem::path(path).filename().string();
        s.found.push_back(CjkPick{path, file + "#" + std::to_string(index), index});
    }
    return k < s.found.size() ? &s.found[k] : nullptr;
}

ChainFace pinCjk(const CjkPick& p) {
    const Bytes b = pin(p.path);
    if (b == nullptr) { return {}; }
    return ChainFace{p.label, b->data(), b->size(), p.index};
}

bool sameFace(const ChainFace& a, const ChainFace& b) {
    return a.data == b.data && a.index == b.index;
}

// The CJK faces a set of code points needs from standard `face`: the first
// usable one, then - only while some of `need` is still missing - the next,
// up to three. None when the machine has no usable face at all.
std::vector<ChainFace> cjkFacesFor(scripts::CjkFace face, const std::vector<unsigned int>& need) {
    std::vector<ChainFace> out;
    if (face == scripts::CjkFace::None) { return out; }
    std::vector<unsigned int> left = need;
    for (std::size_t k = 0; k < 3; ++k) {
        const CjkPick* p = usableCjk(face, k);
        if (p == nullptr) { break; }
        const ChainFace f = pinCjk(*p);
        if (f.data == nullptr) { continue; }
        const std::size_t before = left.size();
        const fontprobe::Face probe{f.data, f.len, f.index};
        left.erase(std::remove_if(left.begin(), left.end(),
                                  [&](unsigned int cp) { return fontprobe::has(probe, cp); }),
                   left.end());
        // The first is always taken - it is THE face for this standard; a
        // later one only for what it adds.
        if (k == 0 || left.size() < before) { out.push_back(f); }
        if (left.empty()) { break; }
    }
    return out;
}

// --- what the atlas holds now -------------------------------------------------

std::string gPair;
// The planned chain of each role as it stands in the atlas, and - behind the
// UI chain only - the faces added so the language list can draw names.
std::vector<ChainFace> gChainUi, gChainLegend, gChainReading;
std::vector<ChainFace> gNamesUi;
std::string gWantLanguage = "en";
bool gWantNames = false;
bool gNamesDone = false;  // names faces added for the chain in force
bool gDirty = false;
// The pair the interface THEME asks for first (setPreferredPair); empty is the
// application's own order - Georgia, then Saira, then Noto.
std::string gPreferPair;

// The em every face in a role is drawn at: its REFERENCE face's, the one
// English is lettered in here (fonts.hpp says why).
float emScale(const ChainFace& face, const ChainFace& ref) {
    if (sameFace(face, ref)) { return 1.0f; }
    const float a = fontprobe::emSpan({face.data, face.len, face.index});
    const float b = fontprobe::emSpan({ref.data, ref.len, ref.index});
    return (a > 0.0f && b > 0.0f) ? a / b : 1.0f;
}

ChainFace uiReference() {
    return haveGeorgia() ? gGeorgia
                         : embedded("Saira Condensed Medium", fontdata::kFontUiTtf, fontdata::kFontUiTtfLen);
}
ChainFace legendReference() {
    return haveGeorgia() ? gGeorgiaBold
                         : embedded("Saira Condensed SemiBold", fontdata::kFontLegendTtf,
                                    fontdata::kFontLegendTtfLen);
}
ChainFace readingReference() {
    return embedded("Nova Mono", fontdata::kFontReadingTtf, fontdata::kFontReadingTtfLen);
}

// One role's chain into the atlas, as ONE ImFont: the first face at the
// role's size, every later one merged into it.
//
// FontDataOwnedByAtlas = false on every source, and it is not optional: the
// embedded bytes are a constexpr array in read-only storage and the system
// files are pinned for the life of the process. ImGui's default is to take
// ownership and free() the pointer when the atlas is destroyed, which on this
// data is a heap corruption at shutdown - and shutdown is exactly where nobody
// looks for one. The const_cast is for AddFontFromMemoryTTF's non-const
// parameter, which exists for that ownership case; neither rasteriser ImGui
// ships writes to font data.
ImFont* addChain(const std::vector<ChainFace>& faces, float size, const ChainFace& ref,
                 const char* role, std::vector<ChainFace>& added) {
    ImFontAtlas* atlas = ImGui::GetIO().Fonts;
    ImFont* font = nullptr;
    added.clear();
    for (std::size_t i = 0; i < faces.size(); ++i) {
        const ChainFace& f = faces[i];
        if (f.data == nullptr) { continue; }
        ImFontConfig cfg;
        cfg.FontDataOwnedByAtlas = false;
        cfg.FontNo = static_cast<ImU32>(f.index);
        cfg.ExtraSizeScale = emScale(f, ref);
        // Shows up in the Metrics/Debug window, so a font problem can be
        // diagnosed by looking rather than by guessing which face is wrong.
        std::snprintf(cfg.Name, sizeof(cfg.Name), "%s: %s", role, f.label.c_str());
        if (font != nullptr) {
            cfg.MergeMode = true;
            cfg.DstFont = font;
        }
        // A missing or unreadable source is survivable here - the chain simply
        // lacks it - so ImGui is asked not to assert on it.
        cfg.Flags |= ImFontFlags_NoLoadError;
        ImFont* got = atlas->AddFontFromMemoryTTF(const_cast<unsigned char*>(f.data),
                                                  static_cast<int>(f.len), font == nullptr ? size : 0.0f,
                                                  &cfg);
        if (got == nullptr) { continue; }
        font = got;
        added.push_back(f);
    }
    return font;
}

// Merges `faces` behind an existing role font.
void extendChain(ImFont* font, const std::vector<ChainFace>& faces, const ChainFace& ref,
                 const char* role, std::vector<ChainFace>& added) {
    if (font == nullptr) { return; }
    for (const ChainFace& f : faces) {
        ImFontConfig cfg;
        cfg.FontDataOwnedByAtlas = false;
        cfg.FontNo = static_cast<ImU32>(f.index);
        cfg.ExtraSizeScale = emScale(f, ref);
        cfg.MergeMode = true;
        cfg.DstFont = font;
        cfg.Flags |= ImFontFlags_NoLoadError;
        std::snprintf(cfg.Name, sizeof(cfg.Name), "%s: %s", role, f.label.c_str());
        if (ImGui::GetIO().Fonts->AddFontFromMemoryTTF(const_cast<unsigned char*>(f.data),
                                                      static_cast<int>(f.len), 0.0f, &cfg) != nullptr) {
            added.push_back(f);
        }
    }
}

bool startsWith(const std::vector<ChainFace>& whole, const std::vector<ChainFace>& prefix) {
    if (prefix.size() > whole.size()) { return false; }
    for (std::size_t i = 0; i < prefix.size(); ++i) {
        if (!sameFace(whole[i], prefix[i])) { return false; }
    }
    return true;
}

std::vector<ChainFace> tail(const std::vector<ChainFace>& whole, std::size_t from) {
    return std::vector<ChainFace>(whole.begin() + static_cast<std::ptrdiff_t>(from), whole.end());
}

// The whole atlas, from nothing: the three role chains, the UI face made
// ImGui's default. Returns false (and leaves ImGui's own font) when a role's
// first face could not be added.
bool rebuild(const Chain& c) {
    ImGuiIO& io = ImGui::GetIO();
    io.Fonts->ClearFonts();
    gNamesUi.clear();
    gNamesDone = false;
    // ORDER MATTERS ONLY IN ONE RESPECT: the first face added becomes ImGui's
    // default, so the UI face goes first and everything that never pushes a
    // font gets the right one for free.
    gUi = addChain(c.ui, kUiSize, uiReference(), "UI", gChainUi);
    gLegend = addChain(c.legend, kLegendSize, legendReference(), "Legend", gChainLegend);
    gReading = addChain(c.reading, kReadingSize, readingReference(), "Reading", gChainReading);
    if (gUi == nullptr || gLegend == nullptr || gReading == nullptr) {
        // Put the atlas back to a state that can definitely draw. A half-loaded
        // atlas is worse than none: it renders some strings and silently drops
        // others depending on which face a call site happened to push.
        io.Fonts->ClearFonts();
        gUi = gLegend = gReading = nullptr;
        gChainUi.clear();
        gChainLegend.clear();
        gChainReading.clear();
        gPair.clear();
        io.Fonts->AddFontDefault();
        return false;
    }
    gPair = c.pair;
    // The style's base size has to agree with the face just made default, or
    // every height derived from GetTextLineHeight is computed against a size
    // nothing is actually drawn at.
    ImGui::GetStyle().FontSizeBase = kUiSize;
    io.FontDefault = gUi;
    return true;
}

// THE LANGUAGE LIST'S NAMES. Each language is listed by its own name -
// "日本語", "한국어" - which the chain in force (English, say) cannot draw.
// For every language this machine CAN draw whose name still has a character
// nothing in the UI chain has, its standard's own face is merged in behind
// the chain; checked again after each addition, so one YaHei that already
// draws "简体中文", "繁體中文" and "日本語" is the only Chinese face added.
// Returns true when anything was.
bool addNamesFaces() {
    bool added = false;
    for (const cascade::i18n::Language& l : cascade::i18n::languages()) {
        std::vector<unsigned int> cps;
        for (std::size_t i = 0; i < l.name.size();) {
            const unsigned int cp = cascade::core::utf8Decode(l.name, i);
            if (scripts::isCjk(cp)) { cps.push_back(cp); }
        }
        if (cps.empty()) { continue; }
        const scripts::CjkFace face = scripts::cjkFaceFor(l.code, cps);
        if (face == scripts::CjkFace::None || !canDraw(l.code)) { continue; }
        auto drawn = [&](unsigned int cp) {
            for (const auto* chain : {&gChainUi, &gNamesUi}) {
                for (const ChainFace& f : *chain) {
                    if (fontprobe::has({f.data, f.len, f.index}, cp)) { return true; }
                }
            }
            return false;
        };
        if (std::all_of(cps.begin(), cps.end(), drawn)) { continue; }
        const std::vector<ChainFace> sys = cjkFacesFor(face, cps);
        if (sys.empty()) { continue; }
        extendChain(gUi, {sys.front()}, uiReference(), "UI names", gNamesUi);
        added = true;
    }
    return added;
}

}  // namespace

std::string systemFontPath(const char* file) {
    if (file == nullptr || file[0] == '\0') { return {}; }
#ifdef _WIN32
    // %WINDIR%\Fonts is where every Windows since 3.1 has kept them; the
    // environment variable is honoured over the usual drive letter because a
    // Windows installed anywhere else still sets it.
    const char* win = std::getenv("WINDIR");
    const std::string root = (win != nullptr && win[0] != '\0') ? std::string(win) : "C:\\Windows";
    return root + "\\Fonts\\" + file;
#else
    (void)file;
    return {};
#endif
}

bool usingSystemSerif() { return gSystemSerif; }

ImFont* ui() { return orCurrent(gUi); }
ImFont* legend() { return orCurrent(gLegend); }
ImFont* reading() { return orCurrent(gReading); }

Chain planChain(const std::string& languageCode) {
    Chain c;
    const std::vector<unsigned int> cps = cascade::i18n::codePoints(languageCode);
    std::vector<unsigned int> letters;  // what the PAIR must have
    std::vector<unsigned int> cjk;      // what the system CJK face must have
    for (const unsigned int cp : cps) {
        if (scripts::isCjk(cp)) {
            cjk.push_back(cp);
        } else if (scripts::isLetter(cp)) {
            letters.push_back(cp);
        }
    }

    const ChainFace notoUi = embedded("Noto Sans Condensed Medium", fontdata::kFontFallbackUiTtf,
                                      fontdata::kFontFallbackUiTtfLen);
    const ChainFace notoLegend = embedded("Noto Sans Condensed SemiBold",
                                          fontdata::kFontFallbackLegendTtf,
                                          fontdata::kFontFallbackLegendTtfLen);
    struct Pair {
        const char* name;
        ChainFace ui, legend;
    };
    std::vector<Pair> pairs;
    if (haveGeorgia()) { pairs.push_back({"Georgia", gGeorgia, gGeorgiaBold}); }
    pairs.push_back({"Saira Condensed",
                     embedded("Saira Condensed Medium", fontdata::kFontUiTtf, fontdata::kFontUiTtfLen),
                     embedded("Saira Condensed SemiBold", fontdata::kFontLegendTtf,
                              fontdata::kFontLegendTtfLen)});
    pairs.push_back({"Noto Sans Condensed", notoUi, notoLegend});
    // THE THEME'S PAIR GOES FIRST when it names one (gui/theme.hpp,
    // preferredFontPair) - and still only wins if it has every letter the
    // catalogue needs, so a theme can never cost a language its glyphs.
    if (!gPreferPair.empty()) {
        std::stable_partition(pairs.begin(), pairs.end(),
                              [](const Pair& q) { return gPreferPair == q.name; });
    }

    // THE FIRST PAIR WITH EVERY LETTER. When none has them all (a stray
    // character nothing embedded draws), the one missing fewest, earliest on
    // a tie - so a single odd letter never costs a language its usual face.
    std::size_t best = 0;
    std::size_t bestMissing = static_cast<std::size_t>(-1);
    for (std::size_t i = 0; i < pairs.size(); ++i) {
        const std::size_t m =
            fontprobe::missing({pairs[i].ui.data, pairs[i].ui.len, 0}, letters) +
            fontprobe::missing({pairs[i].legend.data, pairs[i].legend.len, 0}, letters);
        if (m < bestMissing) {
            best = i;
            bestMissing = m;
        }
        if (m == 0) { break; }
    }
    const Pair& p = pairs[best];
    c.pair = p.name;
    const bool isNoto = sameFace(p.ui, notoUi);
    c.ui = {p.ui};
    c.legend = {p.legend};
    if (!isNoto) {
        c.ui.push_back(notoUi);
        c.legend.push_back(notoLegend);
    }
    c.reading = {readingReference(), notoUi};

    const scripts::CjkFace face = scripts::cjkFaceFor(languageCode, cps);
    c.cjk = static_cast<int>(face);
    if (face != scripts::CjkFace::None) {
        // The probe as well as the catalogue's own characters: a face chosen
        // for a half-finished catalogue must still be right for the whole.
        std::vector<unsigned int> need = cjk;
        for (const unsigned int cp : scripts::probeCodePoints(face)) { need.push_back(cp); }
        const std::vector<ChainFace> sys = cjkFacesFor(face, need);
        c.cjkFound = !sys.empty();
        for (const ChainFace& f : sys) {
            c.ui.push_back(f);
            c.legend.push_back(f);
            c.reading.push_back(f);
        }
    }
    return c;
}

namespace {

// Which CJK standard a language needs, remembered: the language list asks for
// every language on every frame it is open, and working it out walks the whole
// catalogue. Keyed by the catalogue's own identity as well as its code, so a
// translator's file that REPLACES a catalogue (FOXSDR_LANG_FILE) is judged
// afresh.
scripts::CjkFace faceOf(const std::string& code) {
    static std::map<std::string, std::pair<const void*, scripts::CjkFace>> cache;
    const void* id = cascade::i18n::findLanguage(code);
    if (const auto it = cache.find(code); it != cache.end() && it->second.first == id) {
        return it->second.second;
    }
    const scripts::CjkFace face = scripts::cjkFaceFor(code, cascade::i18n::codePoints(code));
    cache[code] = {id, face};
    return face;
}

}  // namespace

bool canDraw(const std::string& languageCode) {
    const scripts::CjkFace face = faceOf(languageCode);
    return face == scripts::CjkFace::None || usableCjk(face, 0) != nullptr;
}

const char* unavailableReason(const std::string& languageCode) {
    if (canDraw(languageCode)) { return ""; }
    return scripts::missingFontReason(faceOf(languageCode), kWindows);
}

void applyLanguage(const std::string& languageCode) {
    if (languageCode != gWantLanguage) {
        gWantLanguage = languageCode;
        gDirty = true;
    }
}

void setPreferredPair(const std::string& pair) {
    if (pair != gPreferPair) {
        gPreferPair = pair;
        gDirty = true;
    }
}

void requestLanguageNames() {
    if (!gWantNames) {
        gWantNames = true;
        gDirty = true;
    }
}

bool applyPending() {
    if (!gDirty || gUi == nullptr) { return false; }
    gDirty = false;
    const Chain c = planChain(gWantLanguage);
    bool changed = false;
    // EXTEND ONLY WHEN NOTHING AHEAD MOVES: the same pair, the atlas's chains
    // are where the plan's begin, and - when the plan adds a face - no names
    // face sits in the way (a Japanese chain appended BEHIND a YaHei added for
    // the list would draw its kanji in Chinese forms). Anything else rebuilds.
    const bool samePrefix = c.pair == gPair && startsWith(c.ui, gChainUi) &&
                            startsWith(c.legend, gChainLegend) &&
                            startsWith(c.reading, gChainReading);
    const auto ui = samePrefix ? tail(c.ui, gChainUi.size()) : std::vector<ChainFace>();
    const auto lg = samePrefix ? tail(c.legend, gChainLegend.size()) : std::vector<ChainFace>();
    const auto rd = samePrefix ? tail(c.reading, gChainReading.size()) : std::vector<ChainFace>();
    const bool grows = !ui.empty() || !lg.empty() || !rd.empty();
    if (!samePrefix || (grows && !gNamesUi.empty())) {
        changed = rebuild(c);  // which forgets the names faces; found again below
    } else if (grows) {
        extendChain(gUi, ui, uiReference(), "UI", gChainUi);
        extendChain(gLegend, lg, legendReference(), "Legend", gChainLegend);
        extendChain(gReading, rd, readingReference(), "Reading", gChainReading);
        changed = true;
    }
    if (gWantNames && !gNamesDone && gUi != nullptr) {
        gNamesDone = true;
        changed = addNamesFaces() || changed;
    }
    return changed;
}

const std::string& pairInUse() { return gPair; }

std::vector<std::string> uiChainLabels() {
    // Read back from the ATLAS, in the order ImGui will ask the sources for a
    // glyph - not from this file's own lists, which say what was meant rather
    // than what is there.
    std::vector<std::string> out;
    if (gUi == nullptr) { return out; }
    for (const ImFontConfig* src : gUi->Sources) {
        const std::string name = src->Name;
        const std::size_t colon = name.find(": ");
        const std::string label = colon == std::string::npos ? name : name.substr(colon + 2);
        const bool names = name.rfind("UI names:", 0) == 0;
        out.push_back(names ? label + " (names)" : label);
    }
    return out;
}

bool load() {
    // GEORGIA FIRST, SAIRA IF IT IS NOT THERE (0.84.0), and taken as a pair: a
    // Georgia body with a Saira Condensed legend, or the reverse, would be two
    // typefaces that were never designed to sit together, so if either file
    // is missing both roles fall back to the embedded pair. planChain("en")
    // makes exactly that choice, English having no letter either pair lacks.
    gSystemSerif = haveGeorgia();
    gWantLanguage = "en";
    gWantNames = false;
    gNamesDone = false;
    gDirty = false;
    const bool ok = rebuild(planChain("en"));
    // From here on the language rules ask this file whether a catalogue can be
    // drawn, so neither "auto" nor a saved choice lands on one that cannot.
    cascade::i18n::setDrawablePredicate(&canDraw);
    return ok;
}

// --- Raw bytes, for callers that are not ImGui -------------------------------
//
// These exist so the remote interface can serve the SAME faces to a browser;
// see gui/font_blobs.hpp. They are defined here because this is already the one
// translation unit that includes font_assets.hpp, and the whole point of that
// restriction is not to compile three megabytes of initialiser twice.
//
// The first three return the upstream files unchanged, which is what the SIL
// Open Font License requires of a Reserved Font Name: redistribution yes,
// modification while keeping the name no. The two fallback faces are the
// subset tools/subset-noto.py cuts; Noto reserves no name.

const unsigned char* uiTtf() { return fontdata::kFontUiTtf; }
std::size_t uiTtfLen() { return fontdata::kFontUiTtfLen; }

const unsigned char* legendTtf() { return fontdata::kFontLegendTtf; }
std::size_t legendTtfLen() { return fontdata::kFontLegendTtfLen; }

const unsigned char* readingTtf() { return fontdata::kFontReadingTtf; }
std::size_t readingTtfLen() { return fontdata::kFontReadingTtfLen; }

const unsigned char* fallbackUiTtf() { return fontdata::kFontFallbackUiTtf; }
std::size_t fallbackUiTtfLen() { return fontdata::kFontFallbackUiTtfLen; }

const unsigned char* fallbackLegendTtf() { return fontdata::kFontFallbackLegendTtf; }
std::size_t fallbackLegendTtfLen() { return fontdata::kFontFallbackLegendTtfLen; }

}  // namespace cascade::gui::fonts
