// Replays a corpus directory through one fuzz target, as an ordinary test.
//
//   fuzz_corpus_replay <target> <file-or-directory>...
//
// WHY THIS EXISTS. A fuzz target is a function, LLVMFuzzerTestOneInput, and
// libFuzzer is only one way to call it. This is the other: it feeds every file
// of the target's regression corpus - the seeds, and every input that ever
// crashed something - to that same function once, in a fixed order, and fails
// if the process faults. Registered with CTest, it runs on every platform in
// the normal suite and, in a sanitizer build, under AddressSanitizer: so a bug
// a fuzzer found once cannot come back unnoticed even where libFuzzer does not
// exist (GCC has none, and MSVC needs an optional component), and a regression
// is caught by the same `ctest` run that catches everything else.
//
// An empty corpus is an ERROR, not a pass: a path typo or a deleted directory
// would otherwise turn a regression test into a silent no-op.
//
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <string>
#include <vector>

namespace fs = std::filesystem;

// One declaration per target, generated by tests/fuzz/fuzz.cmake from the list
// of targets. Each target's own file defines LLVMFuzzerTestOneInput; the build
// renames it per target (a -D on that source) so they can live in one program.
extern "C" {
#define CASCADE_FUZZ_TARGET(name) int cascade_fuzz_##name(const std::uint8_t*, std::size_t);
#include "fuzz_targets.inc"
#undef CASCADE_FUZZ_TARGET
}

namespace {

using Entry = int (*)(const std::uint8_t*, std::size_t);

struct Target {
    const char* name;
    Entry entry;
};

const Target kTargets[] = {
#define CASCADE_FUZZ_TARGET(name) {#name, &cascade_fuzz_##name},
#include "fuzz_targets.inc"
#undef CASCADE_FUZZ_TARGET
};

void collect(const fs::path& p, std::vector<fs::path>& out) {
    std::error_code ec;
    if (fs::is_directory(p, ec)) {
        std::vector<fs::path> here;
        for (const fs::directory_entry& e : fs::recursive_directory_iterator(p, ec)) {
            if (e.is_regular_file(ec)) { here.push_back(e.path()); }
        }
        std::sort(here.begin(), here.end());  // a fixed order, so a failure replays the same way
        out.insert(out.end(), here.begin(), here.end());
    } else if (fs::is_regular_file(p, ec)) {
        out.push_back(p);
    }
}

}  // namespace

int main(int argc, char** argv) {
    if (argc < 3) {
        std::fprintf(stderr, "usage: %s <target> <file-or-directory>...\n", argv[0]);
        return 2;
    }
    const Target* target = nullptr;
    for (const Target& t : kTargets) {
        if (std::strcmp(t.name, argv[1]) == 0) { target = &t; }
    }
    if (target == nullptr) {
        std::fprintf(stderr, "no fuzz target named \"%s\"\n", argv[1]);
        return 2;
    }

    std::vector<fs::path> inputs;
    for (int i = 2; i < argc; ++i) { collect(fs::path(argv[i]), inputs); }
    if (inputs.empty()) {
        std::fprintf(stderr, "FAIL %s: no corpus files found under the given paths\n", target->name);
        return 2;
    }

    std::size_t bytes = 0;
    for (const fs::path& p : inputs) {
        std::ifstream f(p, std::ios::binary);
        const std::vector<char> data((std::istreambuf_iterator<char>(f)),
                                     std::istreambuf_iterator<char>());
        bytes += data.size();
        // Handed over in a buffer of exactly its size, never a larger one with
        // a tail of zeros: an over-read must reach the allocator's red zone.
        std::vector<std::uint8_t> exact(data.size());
        if (!data.empty()) { std::memcpy(exact.data(), data.data(), data.size()); }
        target->entry(exact.data(), exact.size());
    }
    std::printf("fuzz_corpus_%s: %zu inputs, %zu bytes, no fault\n", target->name, inputs.size(),
                bytes);
    return 0;
}
