// i18n.cpp - the catalogue store behind tr() and trId(). See i18n.hpp for the
// contract; this file is how it is kept.
//
// THE STORE ONLY GROWS. Every catalogue ever added lives in gAll until the
// process ends, and "switching language" is one atomic pointer moving from
// one of them to another. That is the whole of the pointer-lifetime promise
// the header makes: a string tr() handed out belongs to a catalogue nothing
// ever frees, so a table built from tr() results in one language is still
// readable - merely in the old language - after the user picks another.
// Replacing a catalogue (a test re-adding "pt-BR") is the same rule: the new
// one takes the code's place for later lookups, the old one stays in gAll.
//
// tr() TAKES NO LOCK. A published catalogue is never modified again, and the
// active pointer is stored with release and read with acquire, so a reader
// on any thread sees either the old catalogue whole or the new one whole.
// trId() does take one, for its cache of composed "text###label" strings -
// the only thing here that is written after publication. It is an
// unordered_map because its nodes do not move when it rehashes, so the
// c_str() of an entry is as permanent as the catalogue it belongs to.
//
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
#include "core/i18n.hpp"

#include <algorithm>
#include <atomic>
#include <cctype>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <memory>
#include <mutex>
#include <string_view>
#include <unordered_map>

#include <nlohmann/json.hpp>

#ifdef _WIN32
#include <windows.h>
#endif

// The only translation unit that includes the generated bytes.
#include "core/lang_assets.hpp"

namespace cascade::i18n {
namespace {

// Heterogeneous lookup, so tr("Band plan") finds its entry through a
// string_view instead of building a std::string - tr() runs several hundred
// times a frame and an allocation apiece would be a real cost for nothing.
struct StringHash {
    using is_transparent = void;
    std::size_t operator()(std::string_view s) const noexcept {
        return std::hash<std::string_view>{}(s);
    }
};
using StringMap = std::unordered_map<std::string, std::string, StringHash, std::equal_to<>>;

struct Catalogue {
    Language info;
    StringMap strings;  // English key -> translation; frozen once published
    StringMap idCache;  // label -> composed trId result; guarded by gMutex
};

const Language kEnglish{"en", "English", "English", false, 0};

std::mutex gMutex;
std::vector<std::unique_ptr<Catalogue>> gAll;  // never shrinks - see the top
std::vector<Catalogue*> gLive;                 // one per code: what lookups see
std::vector<Language> gLanguages{kEnglish};    // languages()'s answer
std::atomic<Catalogue*> gActive{nullptr};      // null = English
std::once_flag gEmbeddedOnce;

std::string lower(std::string_view s) {
    std::string out(s);
    for (char& c : out) {
        if (c >= 'A' && c <= 'Z') { c = static_cast<char>(c - 'A' + 'a'); }
    }
    return out;
}

bool iequals(std::string_view a, std::string_view b) { return lower(a) == lower(b); }

std::string primarySubtag(std::string_view tag) {
    const std::size_t dash = tag.find('-');
    return lower(tag.substr(0, dash));
}

// A BCP 47-shaped code: a 2-3 letter language, then subtags of 2-8 letters
// or digits. Not a full validator - just enough that a code can be a file
// name, a config value and a label without surprising anything.
bool plausibleCode(const std::string& code) {
    std::size_t i = 0;
    std::size_t n = 0;
    while (i < code.size() && std::isalpha(static_cast<unsigned char>(code[i])) != 0) { ++i; ++n; }
    if (n < 2 || n > 3) { return false; }
    while (i < code.size()) {
        if (code[i] != '-') { return false; }
        ++i;
        n = 0;
        while (i < code.size() && std::isalnum(static_cast<unsigned char>(code[i])) != 0) { ++i; ++n; }
        if (n < 2 || n > 8) { return false; }
    }
    return true;
}

// Under gMutex. English first, then the catalogues by English name - the
// order a settings list reads in whatever language it is drawn.
void rebuildLanguagesLocked() {
    std::vector<Language> out;
    out.reserve(gLive.size() + 1);
    out.push_back(kEnglish);
    std::vector<const Catalogue*> sorted(gLive.begin(), gLive.end());
    std::sort(sorted.begin(), sorted.end(), [](const Catalogue* a, const Catalogue* b) {
        return a->info.englishName != b->info.englishName
                   ? a->info.englishName < b->info.englishName
                   : a->info.code < b->info.code;
    });
    for (const Catalogue* c : sorted) { out.push_back(c->info); }
    gLanguages = std::move(out);
}

// The whole of addCatalogue except loading the embedded set first, so the
// embedded loader can call it from inside its own call_once.
bool addCatalogueImpl(const std::string& text, std::string* error,
                      std::vector<std::string>* warnings) {
    auto fail = [error](const std::string& why) {
        if (error != nullptr) { *error = why; }
        return false;
    };
    nlohmann::json j;
    try {
        j = nlohmann::json::parse(text);
    } catch (const nlohmann::json::exception& e) {
        return fail(std::string("not valid JSON: ") + e.what());
    }
    if (!j.is_object()) { return fail("the document is not a JSON object"); }

    auto cat = std::make_unique<Catalogue>();
    auto needString = [&j](const char* key, std::string& out) {
        const auto it = j.find(key);
        if (it == j.end() || !it->is_string()) { return false; }
        out = it->get<std::string>();
        return !out.empty();
    };
    if (!needString("code", cat->info.code)) { return fail("\"code\" is missing or not a string"); }
    if (!plausibleCode(cat->info.code)) {
        return fail("\"code\" is not a language tag: " + cat->info.code);
    }
    if (iequals(cat->info.code, "en")) {
        return fail("English is not a catalogue: tr() already answers in English");
    }
    if (!needString("name", cat->info.name)) { return fail("\"name\" is missing or not a string"); }
    if (!needString("englishName", cat->info.englishName)) {
        return fail("\"englishName\" is missing or not a string");
    }
    if (const auto m = j.find("machine"); m != j.end()) {
        if (!m->is_boolean()) { return fail("\"machine\" is not true or false"); }
        cat->info.machine = m->get<bool>();
    }
    const auto strings = j.find("strings");
    if (strings == j.end() || !strings->is_object()) {
        return fail("\"strings\" is missing or not an object");
    }
    // A value of the wrong TYPE is a broken file, and refused whole; an EMPTY
    // or unsafe translation is one entry nobody finished, and is left out so
    // that key shows in English - the same thing a missing entry does.
    for (auto it = strings->begin(); it != strings->end(); ++it) {
        if (!it.value().is_string()) {
            return fail("the translation of \"" + it.key() + "\" is not a string");
        }
    }
    auto warn = [warnings](const std::string& w) {
        if (warnings != nullptr) { warnings->push_back(w); }
    };
    for (auto it = strings->begin(); it != strings->end(); ++it) {
        const std::string& key = it.key();
        std::string value = it.value().get<std::string>();
        if (key.empty()) {
            warn("an entry with an empty key");
            continue;
        }
        if (value.empty()) {
            warn("\"" + key + "\" has no translation");
            continue;
        }
        // "##" inside a translation would be read by ImGui as the start of an
        // id, cutting the visible text short and changing the widget's id.
        if (value.find("##") != std::string::npos) {
            warn("\"" + key + "\" has ## in its translation");
            continue;
        }
        // The one check here that prevents a CRASH rather than a wrong word:
        // a format string whose conversions differ from its key's reads the
        // wrong arguments. test_i18n refuses such a catalogue; this refuses
        // the entry again in case one ever reaches a build anyway.
        if (formatSpecs(key.c_str()) != formatSpecs(value.c_str())) {
            warn("\"" + key + "\" has different printf conversions in its translation");
            continue;
        }
        cat->strings.emplace(key, std::move(value));
    }
    cat->info.translated = cat->strings.size();

    std::lock_guard<std::mutex> lock(gMutex);
    Catalogue* added = cat.get();
    gAll.push_back(std::move(cat));
    bool replaced = false;
    for (Catalogue*& live : gLive) {
        if (live->info.code == added->info.code) {
            if (gActive.load(std::memory_order_acquire) == live) {
                gActive.store(added, std::memory_order_release);
            }
            live = added;
            replaced = true;
            break;
        }
    }
    if (!replaced) { gLive.push_back(added); }
    rebuildLanguagesLocked();
    return true;
}

// The compiled-in catalogues, once, the first time anything asks which
// languages exist. A catalogue that does not load is a build that shipped a
// broken file past test_i18n; it is skipped with a line on stderr rather than
// allowed to stop the application, because English still works.
void loadEmbedded() {
    for (const langdata::LangFile* f = langdata::kLangFiles; f->name != nullptr; ++f) {
        const std::string text(reinterpret_cast<const char*>(f->bytes), f->len);
        std::string error;
        std::vector<std::string> warnings;
        if (!addCatalogueImpl(text, &error, &warnings)) {
            std::fprintf(stderr, "i18n: catalogue %s skipped: %s\n", f->name, error.c_str());
            continue;
        }
        constexpr std::size_t kShown = 5;
        for (std::size_t i = 0; i < warnings.size() && i < kShown; ++i) {
            std::fprintf(stderr, "i18n: %s: %s\n", f->name, warnings[i].c_str());
        }
        if (warnings.size() > kShown) {
            std::fprintf(stderr, "i18n: %s: and %zu more entries left in English\n", f->name,
                         warnings.size() - kShown);
        }
    }
}

void ensureEmbedded() { std::call_once(gEmbeddedOnce, loadEmbedded); }

Catalogue* liveByCode(const std::string& code) {
    std::lock_guard<std::mutex> lock(gMutex);
    for (Catalogue* c : gLive) {
        if (c->info.code == code) { return c; }
    }
    return nullptr;
}

}  // namespace

const std::vector<Language>& languages() {
    ensureEmbedded();
    return gLanguages;
}

std::string matchCatalogue(const std::string& tag) {
    ensureEmbedded();
    if (tag.empty()) { return {}; }
    std::lock_guard<std::mutex> lock(gMutex);
    for (const Catalogue* c : gLive) {
        if (iequals(c->info.code, tag)) { return c->info.code; }
    }
    // Same language, other country. A catalogue that IS the bare language
    // ("es" for an "es-MX" desktop) is the better answer when there is one;
    // otherwise the first by English name, so the choice does not depend on
    // the order the catalogues happened to be added in.
    const std::string primary = primarySubtag(tag);
    const Catalogue* best = nullptr;
    for (const Catalogue* c : gLive) {
        if (primarySubtag(c->info.code) != primary) { continue; }
        if (lower(c->info.code) == primary) { return c->info.code; }
        if (best == nullptr || c->info.englishName < best->info.englishName) { best = c; }
    }
    return best != nullptr ? best->info.code : std::string();
}

std::string resolveFor(const std::string& setting, const std::string& locale) {
    ensureEmbedded();
    std::string s = setting;
    while (!s.empty() && (s.back() == ' ' || s.back() == '\t')) { s.pop_back(); }
    while (!s.empty() && (s.front() == ' ' || s.front() == '\t')) { s.erase(s.begin()); }
    if (s.empty() || iequals(s, "auto")) {
        const std::string m = matchCatalogue(locale);
        return m.empty() ? std::string("en") : m;
    }
    std::lock_guard<std::mutex> lock(gMutex);
    for (const Catalogue* c : gLive) {
        if (iequals(c->info.code, s)) { return c->info.code; }
    }
    return "en";
}

std::string resolve(const std::string& setting) {
    // The OS is asked only when the setting says to follow it.
    std::string s = lower(setting);
    if (s.empty() || s == "auto") { return resolveFor(setting, systemLocale()); }
    return resolveFor(setting, std::string());
}

std::string setLanguage(const std::string& setting) {
    const std::string code = resolve(setting);
    gActive.store(code == "en" ? nullptr : liveByCode(code), std::memory_order_release);
    return code;
}

const std::string& current() {
    static const std::string kEn = "en";
    const Catalogue* c = gActive.load(std::memory_order_acquire);
    return c != nullptr ? c->info.code : kEn;
}

const Language* findLanguage(const std::string& code) {
    ensureEmbedded();
    if (code == "en") { return &kEnglish; }
    // Into the catalogue itself, not into gLanguages, which is rebuilt on
    // every add: a catalogue's own info never moves.
    const Catalogue* c = liveByCode(code);
    return c != nullptr ? &c->info : nullptr;
}

const char* tr(const char* english) {
    if (english == nullptr) { return nullptr; }
    const Catalogue* c = gActive.load(std::memory_order_acquire);
    if (c == nullptr) { return english; }
    const auto it = c->strings.find(std::string_view(english));
    return it != c->strings.end() ? it->second.c_str() : english;
}

const char* trId(const char* label) {
    if (label == nullptr) { return nullptr; }
    Catalogue* c = gActive.load(std::memory_order_acquire);
    if (c == nullptr) { return label; }
    const std::string_view whole(label);
    const std::size_t hashes = whole.find("##");
    // Only an id ("##freq"): nothing is shown, so nothing is translated.
    if (hashes == 0) { return label; }
    const std::string_view visible =
        hashes == std::string_view::npos ? whole : whole.substr(0, hashes);
    const auto hit = c->strings.find(visible);
    if (hit == c->strings.end()) { return label; }

    std::lock_guard<std::mutex> lock(gMutex);
    if (const auto cached = c->idCache.find(whole); cached != c->idCache.end()) {
        return cached->second.c_str();
    }
    // WHY THE ORIGINAL LABEL FOLLOWS "###". ImHashStr restarts its hash at
    // every "###" and skips the three characters, so "Sauver###Save" hashes
    // exactly as "Save" does, and "Sauver###Save##x" as "Save##x" does: the
    // id in every language is the id the English label always had. A label
    // that already carries "###id" keeps it untouched, which hashes the same
    // for the same reason.
    std::string composed = hit->second;
    if (hashes != std::string_view::npos && whole.compare(hashes, 3, "###") == 0) {
        composed.append(whole.substr(hashes));
    } else {
        composed.append("###");
        composed.append(whole);
    }
    const auto [pos, inserted] = c->idCache.emplace(std::string(whole), std::move(composed));
    (void)inserted;
    return pos->second.c_str();
}

bool addCatalogue(const std::string& json, std::string* error,
                  std::vector<std::string>* warnings) {
    ensureEmbedded();
    return addCatalogueImpl(json, error, warnings);
}

std::string addCatalogueFile(const std::string& path, std::FILE* diag) {
    auto say = [&](const std::string& what) {
        if (diag != nullptr) { std::fprintf(diag, "i18n: %s: %s\n", path.c_str(), what.c_str()); }
    };
    std::FILE* f = std::fopen(path.c_str(), "rb");
    if (f == nullptr) {
        say("cannot be opened");
        return {};
    }
    std::string text;
    char buf[4096];
    for (std::size_t got; (got = std::fread(buf, 1, sizeof(buf), f)) > 0;) { text.append(buf, got); }
    std::fclose(f);
    if (text.size() >= 3 && text.compare(0, 3, "\xEF\xBB\xBF") == 0) { text.erase(0, 3); }

    std::string error;
    std::vector<std::string> warnings;
    if (!addCatalogue(text, &error, &warnings)) {
        say("not added: " + error);
        return {};
    }
    // All of them, unlike the compiled-in loader's first five: this list is
    // the translator's to-do list, not noise at somebody else's start-up.
    for (const std::string& w : warnings) { say(w + " - shown in English"); }
    // The code is read back from the document rather than returned by
    // addCatalogue, which has no reason to know it; the parse cannot fail
    // twice.
    const nlohmann::json j = nlohmann::json::parse(text, nullptr, false);
    return j.is_object() && j.contains("code") ? j["code"].get<std::string>() : std::string();
}

std::vector<std::string> formatSpecs(const char* s) {
    std::vector<std::string> out;
    if (s == nullptr) { return out; }
    auto isDigit = [](char c) { return c >= '0' && c <= '9'; };
    const std::size_t n = std::strlen(s);
    std::size_t i = 0;
    while (i < n) {
        if (s[i] != '%') {
            ++i;
            continue;
        }
        const std::size_t start = i;
        std::size_t j = i + 1;
        if (j < n && s[j] == '%') {  // "%%" prints one percent sign
            i = j + 1;
            continue;
        }
        // A positional argument ("%1$s"): part of the specification, so a
        // translation that reorders arguments is compared as written.
        std::size_t k = j;
        while (k < n && isDigit(s[k])) { ++k; }
        if (k > j && k < n && s[k] == '$') { j = k + 1; }
        while (j < n && std::strchr("-+ #0'", s[j]) != nullptr) { ++j; }  // flags
        if (j < n && s[j] == '*') {
            ++j;
        } else {
            while (j < n && isDigit(s[j])) { ++j; }  // width
        }
        if (j < n && s[j] == '.') {  // precision
            ++j;
            if (j < n && s[j] == '*') {
                ++j;
            } else {
                while (j < n && isDigit(s[j])) { ++j; }
            }
        }
        // Length modifiers, longest first so "ll" is not read as "l" then a
        // conversion called 'l'. I64/I32/I are MSVC's own.
        static const char* const kLengths[] = {"hh", "ll", "I64", "I32", "h", "l", "j",
                                               "z",  "t",  "L",   "I"};
        for (const char* len : kLengths) {
            const std::size_t m = std::strlen(len);
            if (j + m <= n && std::strncmp(s + j, len, m) == 0) {
                j += m;
                break;
            }
        }
        const char conv = j < n ? s[j] : '\0';
        if (conv != '\0' && std::strchr("diouxXfFeEgGaAcspn", conv) != nullptr) {
            out.emplace_back(s + start, j + 1 - start);
            i = j + 1;
        } else {
            // Not a well-formed specification. Listed anyway, as "%?" and the
            // text after the percent sign, so it must be matched exactly.
            std::string bad("%?");
            bad.append(s + start + 1, (conv != '\0' ? j + 1 : j) - (start + 1));
            out.push_back(std::move(bad));
            i = conv != '\0' ? j + 1 : j;
        }
    }
    return out;
}

std::string localeFromPosix(const std::string& value) {
    std::string v = value;
    const std::size_t cut = v.find_first_of(".@");
    if (cut != std::string::npos) { v.resize(cut); }
    if (v.empty() || v == "C" || v == "POSIX") { return {}; }
    std::replace(v.begin(), v.end(), '_', '-');
    return v;
}

std::string systemLocale() {
#ifdef _WIN32
    // The UI LANGUAGE, not the regional format: someone in Portugal who runs
    // Windows in English with Portuguese dates has chosen English to read,
    // and "my language" means what they read. GetUserPreferredUILanguages
    // answers a double-null-terminated list, best first.
    ULONG count = 0;
    ULONG size = 0;
    if (GetUserPreferredUILanguages(MUI_LANGUAGE_NAME, &count, nullptr, &size) != FALSE &&
        size > 1) {
        std::wstring buf(size, L'\0');
        if (GetUserPreferredUILanguages(MUI_LANGUAGE_NAME, &count, buf.data(), &size) != FALSE) {
            std::string out;
            for (const wchar_t* p = buf.c_str(); *p != L'\0'; ++p) {
                // Language tags are ASCII by definition; anything else is not
                // a tag this could match, so it ends the read.
                if (*p > 0x7f) { return {}; }
                out.push_back(static_cast<char>(*p));
            }
            if (!out.empty()) { return out; }
        }
    }
    wchar_t name[LOCALE_NAME_MAX_LENGTH] = {};
    if (GetUserDefaultLocaleName(name, LOCALE_NAME_MAX_LENGTH) > 0) {
        std::string out;
        for (const wchar_t* p = name; *p != L'\0'; ++p) {
            if (*p > 0x7f) { return {}; }
            out.push_back(static_cast<char>(*p));
        }
        return out;
    }
    return {};
#else
    // POSIX precedence: the first of these that is SET decides, even when it
    // says "C" - LC_ALL=C is somebody asking for no translation.
    for (const char* var : {"LC_ALL", "LC_MESSAGES", "LANG"}) {
        const char* v = std::getenv(var);
        if (v != nullptr && v[0] != '\0') { return localeFromPosix(v); }
    }
    return {};
#endif
}

std::vector<EmbeddedFile> embeddedCatalogueFiles() {
    std::vector<EmbeddedFile> out;
    for (const langdata::LangFile* f = langdata::kLangFiles; f->name != nullptr; ++f) {
        out.push_back(EmbeddedFile{f->name, f->bytes, f->len});
    }
    return out;
}

}  // namespace cascade::i18n
