"""Turn the vendored OFL typefaces into a C++ header of byte arrays.

WHY THE FONTS ARE IN THE BINARY AND NOT BESIDE IT. A missing font file is not
a cosmetic failure: Dear ImGui falls back to its own 13px bitmap face, every
hard-coded width in the layout was measured against the real one, and the
result is a panel whose legends overhang their keys. A default Program Files
install is read-only to a normal run (see the plugin-directory lesson), so a
font shipped as a loose file is also a font a user can delete or a repair tool
can miss. Compiled in, the bench either exists or the application does not.

WHY THE BYTES ARE UNMODIFIED. Both faces carry a Reserved Font Name under the
SIL Open Font License - "Saira" and "NovaMono" - and clause 3 forbids a
MODIFIED version from using the reserved name. Subsetting a font to the ASCII
this application actually draws would be a modification, so it would have to be
renamed, which needs a name-table rewrite and a font toolchain nobody else
building this repository would have. Bundling the originals verbatim is
explicitly permitted, needs no rename, and costs about 490 KB. That trade was
made deliberately; do not "optimise" it by subsetting without renaming.

Byte arrays rather than string literals, for the same reason the radar assets
are: MSVC caps a single string literal at 16380 bytes, and no escaping scheme
survives arbitrary binary intact.

Run from the repository root:  py -3.14 tools/embed-fonts.py
"""
import io
import os
import sys

SRC = os.path.join('third_party', 'fonts')
OUT = os.path.join('src', 'gui', 'font_assets.hpp')

FONTS = [
    ('kFontUiTtf', 'SairaCondensed-Medium.ttf'),
    ('kFontLegendTtf', 'SairaCondensed-SemiBold.ttf'),
    ('kFontReadingTtf', 'NovaMono.ttf'),
]

HEADER = '''// font_assets.hpp - GENERATED by tools/embed-fonts.py. Do not edit by hand.
//
// The three faces the bench is drawn in, compiled into the binary as bytes.
// Re-run the generator after replacing anything in third_party/fonts:
//     py -3.14 tools/embed-fonts.py
//
// These are the UPSTREAM files byte for byte. Both families carry a Reserved
// Font Name under the SIL Open Font License, so they must not be subsetted or
// otherwise modified while keeping their names. Licences travel with them in
// third_party/fonts/OFL-*.txt and are listed in third_party/THIRD_PARTY.md.
//
// INCLUDE THIS FROM EXACTLY ONE TRANSLATION UNIT (gui/fonts.cpp). It is about
// three megabytes of initialiser and there is no reason to compile it twice.
//
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
#ifndef CASCADE_GUI_FONT_ASSETS_HPP
#define CASCADE_GUI_FONT_ASSETS_HPP

namespace cascade::gui::fontdata {

'''

FOOTER = '''}  // namespace cascade::gui::fontdata

#endif  // CASCADE_GUI_FONT_ASSETS_HPP
'''


def emit(name, path):
    with open(path, 'rb') as f:
        data = f.read()
    # NO newline normalisation here, unlike the radar assets: this is binary,
    # and a TTF full of 0x0d 0x0a pairs would be silently corrupted by it.
    out = []
    out.append('// %s, %d bytes\n' % (os.path.basename(path), len(data)))
    out.append('inline constexpr unsigned char %s[] = {\n' % name)
    for i in range(0, len(data), 24):
        row = ','.join('0x%02x' % b for b in data[i:i + 24])
        out.append(row)
        out.append(',\n')
    out.append('};\n')
    out.append('inline constexpr unsigned int %sLen = %d;\n\n' % (name, len(data)))
    return ''.join(out)


def main():
    if not os.path.isdir(SRC):
        sys.stderr.write('run me from the repository root: %s not found\n' % SRC)
        return 1
    parts = [HEADER]
    total = 0
    for name, filename in FONTS:
        path = os.path.join(SRC, filename)
        if not os.path.isfile(path):
            sys.stderr.write('missing font: %s\n' % path)
            return 1
        total += os.path.getsize(path)
        parts.append(emit(name, path))
    parts.append(FOOTER)
    with io.open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(''.join(parts))
    print('%s: %d fonts, %d bytes of TTF, %d bytes of header'
          % (OUT, len(FONTS), total, os.path.getsize(OUT)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
