"""Turn resources/web/radar/* into a C++ header of byte arrays.

Byte arrays, not string literals, on purpose: MSVC caps a single string
literal at 16380 bytes (web_server.cpp is split into kAppJs1..kAppJs2e for
exactly that reason) and any escaping scheme has to survive backslashes and
non-ASCII intact. An array of bytes has neither problem, and the generated
header is verified byte-for-byte against the sources by a test.

Run from the repository root:  py -3.14 tools/embed-radar-assets.py
"""
import io
import os
import sys

SRC = os.path.join('resources', 'web', 'radar')
OUT = os.path.join('src', 'radar', 'radar_assets.hpp')

FILES = [
    ('kRadarHtml', 'radar.html'),
    ('kRadarCss', 'radar.css'),
    ('kRadarJs', 'radar.js'),
]


def emit(name, path):
    with open(path, 'rb') as f:
        data = f.read()
    # Normalise to LF so a Windows checkout and a Linux one embed identical
    # bytes - otherwise the hash test below fails depending on git's autocrlf.
    data = data.replace(b'\r\n', b'\n')
    out = []
    out.append('// %s, %d bytes\n' % (os.path.basename(path), len(data)))
    out.append('inline constexpr unsigned char %s[] = {\n' % name)
    for i in range(0, len(data), 16):
        row = ', '.join('0x%02x' % b for b in data[i:i + 16])
        out.append('    %s,\n' % row)
    out.append('};\n')
    out.append('inline constexpr unsigned int %sLen = %d;\n\n' % (name, len(data)))
    return ''.join(out)


def main():
    if not os.path.isdir(SRC):
        sys.stderr.write('run from the repository root: %s not found\n' % SRC)
        return 2
    parts = [
        '// GENERATED by tools/embed-radar-assets.py - do not edit by hand.\n',
        '// Source of truth: resources/web/radar/*. Edit those, then re-run the\n',
        '// generator; tests/test_radar_assets.cpp fails if this file drifts.\n',
        '#pragma once\n\n',
        'namespace cascade {\n',
        'namespace radar {\n\n',
    ]
    for name, fn in FILES:
        parts.append(emit(name, os.path.join(SRC, fn)))
    parts.append('}  // namespace radar\n')
    parts.append('}  // namespace cascade\n')
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with io.open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(''.join(parts))
    print('wrote %s (%d bytes)' % (OUT, os.path.getsize(OUT)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
