"""Turn the translation catalogues into a C++ header of byte arrays.

WHY THE CATALOGUES ARE IN THE BINARY AND NOT BESIDE IT. The same argument as
the typefaces (tools/embed-fonts.py): a translation shipped as a loose file is
one more thing each of the five packagers - Inno, MSIX, AppImage, Android and
the CI zip - can leave out, and a catalogue that is missing does not fail. It
falls silently back to English, on somebody else's machine, and nobody files
a bug that says "the Polish went away". Compiled in, a language either exists
in the build or it does not.

WHY BYTES AND NOT STRING LITERALS. MSVC caps a single string literal at 16380
bytes and a machine-translated catalogue of every string in the bench is well
past that; a byte array has no such limit and needs no escaping scheme.

THE BYTES ARE THE FILE, UNCHANGED. Nothing is parsed or normalised here - the
loader in core/i18n.cpp parses at start-up, and tests/test_i18n.cpp compares
these arrays against resources/lang/*.json byte for byte, so a catalogue
edited without re-running this script fails the suite rather than shipping
the old words.

With no catalogues present the header is still generated, with an empty table
(a single terminating entry), so the build never depends on whether any
translation has been written yet.

Run from the repository root:  py -3.14 tools/embed-lang.py
"""
import io
import os
import re
import sys

SRC = os.path.join('resources', 'lang')
OUT = os.path.join('src', 'core', 'lang_assets.hpp')

HEADER = '''// lang_assets.hpp - GENERATED by tools/embed-lang.py. Do not edit by hand.
//
// The interface translations, compiled into the binary as bytes - one array
// per resources/lang/<code>.json, in file-name order, and a table of them
// ending in a {nullptr, nullptr, 0} entry. Re-run the generator after adding
// or editing a catalogue:
//     py -3.14 tools/embed-lang.py
// tests/test_i18n.cpp fails, naming this command, when the bytes here and the
// files on disk disagree.
//
// INCLUDE THIS FROM EXACTLY ONE TRANSLATION UNIT (core/i18n.cpp). Anything
// else that needs the bytes asks i18n::embeddedCatalogueFiles().
//
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
#ifndef CASCADE_CORE_LANG_ASSETS_HPP
#define CASCADE_CORE_LANG_ASSETS_HPP

namespace cascade::i18n::langdata {

struct LangFile {
    const char* name;            // file name, e.g. "pt-BR.json"
    const unsigned char* bytes;  // the file, byte for byte
    unsigned int len;
};

'''

FOOTER = '''}  // namespace cascade::i18n::langdata

#endif  // CASCADE_CORE_LANG_ASSETS_HPP
'''


def ident(filename):
    # "pt-BR.json" -> "kLang_pt_BR"; anything that is not a letter or digit
    # becomes an underscore, which is all a C++ identifier needs.
    stem = filename[:-len('.json')]
    return 'kLang_' + re.sub(r'[^A-Za-z0-9]', '_', stem)


def emit(name, data):
    out = []
    out.append('// %s, %d bytes\n' % (name, len(data)))
    out.append('inline constexpr unsigned char %s[] = {\n' % ident(name))
    for i in range(0, len(data), 24):
        out.append(','.join('0x%02x' % b for b in data[i:i + 24]))
        out.append(',\n')
    out.append('};\n\n')
    return ''.join(out)


def main():
    if not os.path.isdir('src') or not os.path.isdir('resources'):
        sys.stderr.write('run me from the repository root\n')
        return 1
    files = []
    if os.path.isdir(SRC):
        # Sorted by file name, byte order, so the header is identical on every
        # machine whatever order the filesystem lists the directory in.
        files = sorted(f for f in os.listdir(SRC)
                       if f.endswith('.json') and os.path.isfile(os.path.join(SRC, f)))
    seen = set()
    sizes = []
    parts = [HEADER]
    total = 0
    for name in files:
        key = ident(name)
        if key in seen:
            sys.stderr.write('two catalogues map to one identifier: %s\n' % key)
            return 1
        seen.add(key)
        with open(os.path.join(SRC, name), 'rb') as f:
            data = f.read()
        if not data:
            sys.stderr.write('empty catalogue: %s\n' % name)
            return 1
        total += len(data)
        sizes.append(len(data))
        parts.append(emit(name, data))
    parts.append('inline constexpr LangFile kLangFiles[] = {\n')
    for name, size in zip(files, sizes):
        parts.append('    {"%s", %s, %d},\n' % (name, ident(name), size))
    parts.append('    {nullptr, nullptr, 0},\n')
    parts.append('};\n')
    parts.append('inline constexpr unsigned int kLangFileCount = %d;\n\n' % len(files))
    parts.append(FOOTER)
    with io.open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(''.join(parts))
    print('%s: %d catalogues, %d bytes of JSON' % (OUT, len(files), total))
    return 0


if __name__ == '__main__':
    sys.exit(main())
