# Exports a compact RVA -> function-name map from a PDB, for the crash
# dashboard's SYMBOLIC GROUPING (foxsdrWebsite, crash.go).
#
# WHY THE SERVER NEEDS THIS FILE AT ALL. A crash report identifies a frame as
# module + offset, and the client's grouping signature is built from exactly
# that - which measured badly in the field within one release cycle of
# shipping it. The same vendor teardown fault filed on consecutive days landed
# in TWO signatures because a Windows update moved ntdll's offsets; and two
# UNRELATED faults (a fatal 0.62.0 retune and an absorbed 0.64.0 teardown, two
# different users) merged into ONE signature because RtlpWaitOnCriticalSection
# happened to sit at the same RVA in both machines' ntdll builds. Offsets into
# code we do not ship identify the victim's patch level, not the bug.
#
# The stable identity of a fault is the nearest frame in OUR OWN code, BY NAME
# - "SoapySource::teardownLocked" survives every Windows update, every vendor
# driver install, and every FoxSDR release. Names need the PDB, the PDB never
# leaves this machine (it is tens of megabytes and full of paths), and the
# server is a Linux box that could not read it anyway. So the build exports
# THIS: the function table alone, a few hundred kilobytes of JSON, keyed by
# the same build id the report's frames quote. The server looks a frame's
# offset up in the map for its build id and groups by what it finds.
#
# The map is generated by tools/archive-symbols.ps1 on every build, right
# after the PDB itself is archived, into the same symbol-server layout:
#
#     <archive>\<pdb name>\<GUID><AGE>\<pdb name>            the PDB
#     <archive>\<pdb name>\<GUID><AGE>\symmap.json.gz        this map
#
# Deploying a map to the dashboard is copying it to the server's
# data/symbols/<BUILDID>.json.gz - see foxsdrWebsite/symbolmaps/README.md.
#
# Requires dbghelp.dll, i.e. runs on Windows - the same constraint the whole
# symbol archive already has, which is why the map is exported at build time
# rather than resolved at ingest time.
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

import argparse
import ctypes
import ctypes.wintypes as wt
import gzip
import json
import os
import sys

SYMOPT_UNDNAME = 0x2
SYM_TAG_FUNCTION = 5


class SYMBOL_INFOW(ctypes.Structure):
    _fields_ = [
        ("SizeOfStruct", wt.ULONG),
        ("TypeIndex", wt.ULONG),
        ("Reserved", ctypes.c_ulonglong * 2),
        ("Index", wt.ULONG),
        ("Size", wt.ULONG),
        ("ModBase", ctypes.c_ulonglong),
        ("Flags", wt.ULONG),
        ("Value", ctypes.c_ulonglong),
        ("Address", ctypes.c_ulonglong),
        ("Register", wt.ULONG),
        ("Scope", wt.ULONG),
        ("Tag", wt.ULONG),
        ("NameLen", wt.ULONG),
        ("MaxNameLen", wt.ULONG),
        # Variable-length; the callback reads NameLen wchars from here.
        ("Name", ctypes.c_wchar * 1),
    ]


def export(pdb_path: str, module: str, build_id: str, out_path: str) -> int:
    dbghelp = ctypes.WinDLL("dbghelp.dll")
    dbghelp.SymSetOptions(SYMOPT_UNDNAME)

    hproc = ctypes.c_void_p(0x1)  # any unique value; no live process attached
    dbghelp.SymInitializeW.argtypes = [ctypes.c_void_p, wt.LPCWSTR, wt.BOOL]
    if not dbghelp.SymInitializeW(hproc, None, False):
        print(f"export-symbol-map: SymInitialize failed ({ctypes.GetLastError()})",
              file=sys.stderr)
        return 1

    dbghelp.SymLoadModuleExW.restype = ctypes.c_ulonglong
    dbghelp.SymLoadModuleExW.argtypes = [
        ctypes.c_void_p, ctypes.c_void_p, wt.LPCWSTR, wt.LPCWSTR,
        ctypes.c_ulonglong, wt.DWORD, ctypes.c_void_p, wt.DWORD,
    ]
    # Any base works: everything below is stored relative to it.
    base = dbghelp.SymLoadModuleExW(hproc, None, pdb_path, None,
                                    0x10000000, 0, None, 0)
    if base == 0:
        print(f"export-symbol-map: could not load {pdb_path} "
              f"({ctypes.GetLastError()})", file=sys.stderr)
        return 1

    functions = []

    CALLBACK = ctypes.WINFUNCTYPE(wt.BOOL, ctypes.POINTER(SYMBOL_INFOW),
                                  wt.ULONG, ctypes.c_void_p)

    def on_symbol(psym, _size, _ctx):
        s = psym.contents
        # Functions only. Publics, data and thunks would triple the file for
        # frames that never appear as "the nearest frame in our code".
        if s.Tag != SYM_TAG_FUNCTION:
            return True
        # NameLen COUNTS THE TERMINATOR (measured: every name in the first
        # generated maps ended "\x00", which survives JSON round-trips and
        # poisons any consumer comparing names). Strip it — and stray
        # whitespace — at the source.
        name = ctypes.wstring_at(
            ctypes.addressof(s) + SYMBOL_INFOW.Name.offset, s.NameLen)
        # NameLen is NOT trustworthy. Normally it counts the name plus its
        # terminator; on a couple of real cascade symbols it was ~2046 with
        # the true name ending at an interior NUL and the rest dbghelp heap
        # garbage (pointer bytes, lone UTF-16 surrogates that later make the
        # JSON unencodable). The name is whatever precedes the FIRST NUL.
        name = name.split("\x00", 1)[0].strip()
        # Belt and braces for garbage that precedes a NUL: replace rather
        # than crash — one mangled character beats no map for the build.
        name = name.encode("utf-8", errors="replace").decode("utf-8")
        if not name:
            return True
        rva = int(s.Address - base)
        if rva < 0:
            return True
        functions.append((rva, int(s.Size), name))
        return True

    dbghelp.SymEnumSymbolsW.argtypes = [ctypes.c_void_p, ctypes.c_ulonglong,
                                        wt.LPCWSTR, CALLBACK, ctypes.c_void_p]
    cb = CALLBACK(on_symbol)
    if not dbghelp.SymEnumSymbolsW(hproc, ctypes.c_ulonglong(base), "*", cb, None):
        print(f"export-symbol-map: SymEnumSymbols failed "
              f"({ctypes.GetLastError()})", file=sys.stderr)
        return 1

    if not functions:
        # A PDB with no function symbols is a stripped or wrong file; a silent
        # empty map would make every lookup "unresolved" and read as if the
        # feature simply did not work.
        print(f"export-symbol-map: {pdb_path} yielded no function symbols",
              file=sys.stderr)
        return 1

    functions.sort(key=lambda f: f[0])
    # Duplicate starts (identical COMDAT-folded bodies): keep the first name.
    # The fold means the bytes are identical, so either name is truthful.
    deduped = []
    last_rva = -1
    for f in functions:
        if f[0] == last_rva:
            continue
        deduped.append(f)
        last_rva = f[0]

    doc = {
        "schema": 1,
        "module": module,
        "buildId": build_id,
        "functions": [[rva, size, name] for (rva, size, name) in deduped],
    }
    tmp = out_path + ".tmp"
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with gzip.open(tmp, "wt", encoding="utf-8") as fh:
        json.dump(doc, fh, separators=(",", ":"), ensure_ascii=False)
    os.replace(tmp, out_path)
    print(f"export-symbol-map: {module} {build_id}: {len(deduped)} functions "
          f"-> {out_path}")
    return 0


def check(out_path: str, probes: list[int]) -> int:
    # Spot verification: resolve the given RVAs from the WRITTEN file, through
    # the same containment rule the server uses, so what is checked is the
    # artifact rather than the in-memory list it came from.
    with gzip.open(out_path, "rt", encoding="utf-8") as fh:
        doc = json.load(fh)
    fns = doc["functions"]
    for rva in probes:
        lo, hi = 0, len(fns)
        while lo < hi:
            mid = (lo + hi) // 2
            if fns[mid][0] <= rva:
                lo = mid + 1
            else:
                hi = mid
        hit = None
        if lo > 0:
            start, size, name = fns[lo - 1]
            nxt = fns[lo][0] if lo < len(fns) else None
            if (size > 0 and rva < start + size) or \
               (size == 0 and nxt is not None and rva < nxt):
                hit = (name, rva - start)
        if hit is None:
            print(f"  +{rva}  <unresolved>")
        else:
            print(f"  +{rva}  {hit[0]}+0x{hit[1]:x}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pdb", required=True, help="path to the PDB to export")
    ap.add_argument("--module", default="cascade.exe",
                    help="module file name reports will quote (default cascade.exe)")
    ap.add_argument("--build-id", required=True,
                    help="the GUID+age build id, exactly as reports quote it")
    ap.add_argument("--out", required=True, help="output .json.gz path")
    ap.add_argument("--check", type=lambda s: [int(x) for x in s.split(",")],
                    default=None,
                    help="after writing, resolve these comma-separated decimal "
                         "RVAs from the written file and print the names")
    args = ap.parse_args()

    rc = export(args.pdb, args.module, args.build_id, args.out)
    if rc == 0 and args.check:
        rc = check(args.out, args.check)
    return rc


if __name__ == "__main__":
    sys.exit(main())
