#!/usr/bin/env python3
"""Convert Natural Earth coastline GeoJSON into an embeddable C++ header.

Natural Earth is PUBLIC DOMAIN ("All versions of Natural Earth raster + vector
map data found on this website are in the public domain"), which is why it can
be compiled into a product that is sold. OpenStreetMap-derived data could not,
without answering ODbL.

STORAGE. Coordinates are stored as int16 hundredths of a degree:

    lon * 100 spans -18000..18000, lat * 100 spans -9000..9000

both of which fit int16 comfortably. That quantises to 0.01 degrees, about
1.1 km - finer than the 1:110m source data is accurate to, so nothing is lost
that was there to begin with, and it halves the size against float32 and
quarters it against double.

Consecutive duplicate points after quantisation are dropped, and any polyline
left with fewer than two distinct points is discarded: at this resolution a
number of tiny islands collapse to a single point, and a "line" of one vertex
draws nothing while still costing a bounds check every frame.

Usage: py -3.14 make_coastline.py <in.geojson> <out.hpp>
"""

import json
import sys


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    src, dst = sys.argv[1], sys.argv[2]

    with open(src, "r", encoding="utf-8") as fh:
        gj = json.load(fh)

    lines = []
    for feat in gj.get("features", []):
        geom = feat.get("geometry") or {}
        gtype = geom.get("type")
        if gtype == "LineString":
            parts = [geom["coordinates"]]
        elif gtype == "MultiLineString":
            parts = geom["coordinates"]
        else:
            continue
        for part in parts:
            pts = []
            last = None
            for lon, lat in part:
                q = (int(round(lon * 100.0)), int(round(lat * 100.0)))
                # Clamp rather than trust: a stray coordinate outside the
                # world would silently wrap when packed into int16.
                q = (max(-18000, min(18000, q[0])), max(-9000, min(9000, q[1])))
                if q != last:
                    pts.append(q)
                    last = q
            if len(pts) >= 2:
                lines.append(pts)

    total = sum(len(p) for p in lines)

    out = []
    out.append("// GENERATED by scratchpad/make_coastline.py - do not edit.")
    out.append("//")
    out.append("// Source: Natural Earth 1:110m coastline (naturalearthdata.com),")
    out.append("// via github.com/nvkelso/natural-earth-vector.")
    out.append("//")
    out.append("// Natural Earth data is in the PUBLIC DOMAIN: no permission is needed to")
    out.append("// use it, no attribution is required, and there is no share-alike term.")
    out.append("// That is why it can be compiled into a product that is sold - an")
    out.append("// OpenStreetMap-derived basemap could not be, without answering ODbL.")
    out.append("// Credit is given anyway, because it is deserved.")
    out.append("//")
    out.append("// Coordinates are int16 HUNDREDTHS OF A DEGREE (0.01 deg, about 1.1 km),")
    out.append("// which is finer than the 1:110m source is accurate to.")
    out.append("//")
    out.append("// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0")
    out.append("// (the generated file; the DATA it contains is public domain)")
    out.append("")
    out.append("#pragma once")
    out.append("")
    out.append("#include <cstdint>")
    out.append("")
    out.append("namespace cascade::gui::coastline {")
    out.append("")
    out.append("// lon, lat pairs in hundredths of a degree, concatenated.")
    out.append("inline constexpr std::int16_t kCoords[] = {")

    flat = []
    for pts in lines:
        for x, y in pts:
            flat.append(x)
            flat.append(y)
    for i in range(0, len(flat), 16):
        out.append("    " + ",".join(str(v) for v in flat[i:i + 16]) + ",")
    out.append("};")
    out.append("")
    out.append("// Start index (in POINTS, not int16s) and length of each polyline.")
    out.append("struct Run { std::uint32_t first; std::uint32_t count; };")
    out.append("inline constexpr Run kRuns[] = {")
    off = 0
    runs = []
    for pts in lines:
        runs.append((off, len(pts)))
        off += len(pts)
    for i in range(0, len(runs), 8):
        chunk = ", ".join("{%d,%d}" % r for r in runs[i:i + 8])
        out.append("    " + chunk + ",")
    out.append("};")
    out.append("")
    out.append("inline constexpr std::uint32_t kRunCount = %d;" % len(runs))
    out.append("inline constexpr std::uint32_t kPointCount = %d;" % total)
    out.append("")
    out.append("}  // namespace cascade::gui::coastline")
    out.append("")

    with open(dst, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out))

    print("polylines: %d" % len(lines))
    print("points:    %d" % total)
    print("bytes of coordinate data: %d" % (total * 4))
    return 0


if __name__ == "__main__":
    sys.exit(main())
